### ISSUE TITLE
95% CI sometimes doesn't contain the RMSE or MUE

### ISSUE THREAD

**Issue by zhang-ivy** [OpenFreeEnergy/cinnabar#73]
I generated a cinnabar plot for my terminally-blocked amino acid RBFE calc data, comparing the forward vs reverse DDGs, but the RMSE and MUE do not lie within their respective 95% CIs.

![image (19)](https://user-images.githubusercontent.com/35546250/212754333-cd4fe26e-6362-430c-ac54-7a2901b03f2b.png)

Here is the code that does the bootstrapping: https://github.com/OpenFreeEnergy/cinnabar/blob/1dbe248511e179b49d7cb654d22b46ebbd15fd46/cinnabar/stats.py#L111-L130
![image (19)](https://user-images.githubusercontent.com/35546250/212753909-b8c03db9-14d2-42e1-9e66-9f1732d22ceb.png)

@jchodera points out that  "The bootstrapping is both (1) resampling with replacement and (2) adding noise related to the experimental error to the experimental data and noise related to the predicted error in each replicate.
If we intend to capture the finite sample size effect, we only want (1), and do not want to include (2).
Can you try eliminating the extra addition of normal error in lines 117 and 118? You can just say "scale=0*..." to set the scale to zero by just adding the 0* in place rather than rewriting those lines."

When I re-generate the plot with John's suggested fix, the problem goes away: 

![image](https://user-images.githubusercontent.com/35546250/212754648-d1156eb0-3b21-4fd2-a970-bac0a6262e5d.png)

**Comment by IAlibay** [comment]
So part of the "issue" here is that we're using the RMSE (same is true  based on a direct calculation of the RMSE from the x / y inputs (i.e. what's available under the 'mle' key) rather than the mean of the bootstrapped results (i.e. what's available under 'mean' key).

@jchodera are you saying that the noise in the experimental error shouldn't be included at all or that it shouldn't be included based on a given use case? If it's the latter, would it make sense to also report the estimate of the bootstrapped population as means of helping to assess how likely the original sample estimate represents the true value?

**Comment by zhang-ivy** [comment]
From @jchodera: 
We should figure out whether the API should support a fixed version of the old mode ("simulate what would happen if I ran the experiment and calculation many times", where we need to report the mean of the bootstraps, not the MLE) in addition to the scale 0 mode you just implemented ("show me the effects of finite sample size so I can draw some conclusions about how well we fit the data", which I think should be the default)

**Comment by zhang-ivy** [comment]
Tagging @dotsdl and @ijpulidos as well

**Comment by IAlibay** [comment]
Allowing for both is easy enough to deal with, we can just have boostrap_statistics report both and pass an extra argument to plotting as necessary. I probably would ask that we wait for @richardjgowers' refactor though since we would effectively doing a major behaviour change so it makes more sense for that to be incorporated alongside that major object structure change.

**Comment by zhang-ivy** [comment]
@IAlibay : I wasn't aware that cinnabar is being refactored -- what's the status of the refactor / when can we expect it to be done? I was hoping we could get this issue fixed (and cut a bug fix release) by the end of the week, as I (and probably others like @dominicrufa @ijpulidos) need to fix the CIs in our plots ASAP.

**Comment by IAlibay** [comment]
> what's the status of the refactor / when can we expect it to be done? I was hoping we could get this issue fixed (and cut a bug fix release)
I'll let @richardjgowers speak to the progress of the refactor.

That being said I strongly disagree with any behaviour changes being a bugfix, that would be a major breakage of semver. Addition of new features would be a minor version change, addition of a break in behaviour would be a major version change.

**Comment by richardjgowers** [comment]
hi @zhang-ivy the refactor is happening at #72

I'm not sure we can promise a release by the end of the week.

**Comment by dotsdl** [comment]
@zhang-ivy will create the PR addressing this; include `bootstrap_experimental_uncertainty` and `bootstrap_computed_uncertainty` keyword arguments controlling the separate sources of uncertainty.
